services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-crypto_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
